<?php

namespace xframe\authorisation;

require_once dirname(__FILE__) . '/../../../../lib/xframe/authorisation/Acl.php';

/**
 * Test class for Acl.
 * Generated by PHPUnit on 2012-03-16 at 16:58:45.
 */
class AclTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Acl
     */
    protected $acl;

    protected function setUp() {
        $this->acl = new Acl;
        $this->acl->addResource("public")
                  ->addResource("control panel")
                  ->addResource("su panel")
                  ->addRole("anon")
                  ->addRole("user")
                  ->addRole("admin");
    }

    public function testIsAllowed() {

        $this->assertFalse($this->acl->isAllowed("anon", "public"));
        $this->acl->allow("anon", "public");
        $this->assertTrue($this->acl->isAllowed("anon", "public"));
        $this->acl->deny("anon", "public");
        $this->assertFalse($this->acl->isAllowed("anon", "public"));
    }

}
