<?php 

//This file is automatically generated and should not be changed
//It contains the class/file map for the autoloading Factory object
Factory::add('Cache','framework/cache/Cache.php');
Factory::add('Factory','framework/core/Factory.php');
Factory::add('FrameEx','framework/core/FrameEx.php');
Factory::add('Registry','framework/core/Registry.php');
Factory::add('CyclicalRelationshipException','framework/database/CyclicalRelationshipException.php');
Factory::add('DB','framework/database/DB.php');
Factory::add('MissingRecord','framework/database/MissingRecord.php');
Factory::add('MultipleRecord','framework/database/MultipleRecord.php');
Factory::add('Record','framework/database/Record.php');
Factory::add('MalformedPage','framework/display/MalformedPage.php');
Factory::add('Page','framework/display/Page.php');
Factory::add('XML','framework/display/XML.php');
Factory::add('Logger','framework/logging/Logger.php');
Factory::add('LoggerManager','framework/logging/LoggerManager.php');
Factory::add('Dispatcher','framework/request/Dispatcher.php');
Factory::add('Request','framework/request/Request.php');
Factory::add('UnknownRequest','framework/request/UnknownRequest.php');
Factory::add('ArrayUtil','framework/util/ArrayUtil.php');
Factory::add('Encryption','framework/util/Encryption.php');
Factory::add('InputValidator','framework/util/InputValidator.php');
Factory::add('PorterStemmer','framework/util/PorterStemmer.php');
