<?php 

//This file is automatically generated and should not be changed
//It contains the class/file map for the autoloading Factory object
Factory::add('XML','./framework/display/XML.php');
Factory::add('MalformedPage','./framework/display/MalformedPage.php');
Factory::add('Page','./framework/display/Page.php');
Factory::add('ArrayUtil','./framework/util/ArrayUtil.php');
Factory::add('MultipleRecord','./framework/database/MultipleRecord.php');
Factory::add('MissingRecord','./framework/database/MissingRecord.php');
Factory::add('DB','./framework/database/DB.php');
Factory::add('Record','./framework/database/Record.php');
Factory::add('Factory','./framework/core/Factory.php');
Factory::add('FrameEx','./framework/core/FrameEx.php');
Factory::add('Registry','./framework/core/Registry.php');
Factory::add('UnknownEvent','./framework/event/UnknownEvent.php');
Factory::add('Dispatcher','./framework/event/Dispatcher.php');
Factory::add('Event','./framework/event/Event.php');
