#!/bin/bash
scriptpath="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"
report=$scriptpath/../report
source=$scriptpath/../src
tests=$scriptpath/../test

rm $report -Rf
mkdir $report
phpunit --bootstrap=$tests/bootstrap.php --log-junit $report/logfile.xml --coverage-clover $report/coverage/clover.xml --coverage-html $report/coverage-html/ $tests

