<?php

namespace xframe\validation;

/**
 * Test class for Regex.
 * Generated by PHPUnit on 2012-01-13 at 10:09:11.
 */
class RegexTest extends \PHPUnit_Framework_TestCase {

    public function testValidate() {
        $validator = new RegEx('/u[0-9]{3}[a-z]/i');
        $this->assertTrue($validator->validate("U123a"));
        $this->assertFalse($validator->validate("U1234"));
    }

}
